# DOCKER_HOST=ssh://pi4 docker build -f Dockerfile.effektpedal -t compiled .
FROM torgeir/effektpedal:latest
COPY . /effektpedal
WORKDIR effektpedal
RUN cmake -G"CodeBlocks - Unix Makefiles" . && make
WORKDIR /effektpedal/test
#ENTRYPOINT ./EffektPedal_Test_Delay
#ENTRYPOINT ./EffektPedal_Test_Reverb
ENTRYPOINT ./EffektPedal