FROM ubuntu:latest as build
ENV DEBIAN_FRONTEND=noninteractive TZ="Europe/Oslo"
RUN apt update \
    && apt install -y \
    libasound-dev g++ cmake \
    alsa-base alsa-tools alsa-utils
RUN usermod -G audio root
RUN echo pcm.!default plughw:Device >> ~/.asoundrc
RUN echo ctl.!default plughw:Device >> ~/.asoundrc

# publish by:
# docker tag XX <docker-hub-username>/effektpedal
# docker push <docker-hub-username>/effektpedal
